/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { T8 } from "./T8";
export * as factories from "./factories";
export { T8__factory } from "./factories/T8__factory";
